#!/bin/sh
#
# Docker entrypoint
#

# Set up environment
printenv > /etc/environment

# Ensure up-to-date
/etc/cron.daily/get_iplayer_update

# Start cron with output to syslog
/sbin/syslogd
/usr/sbin/cron

# Restart if killed, e.g. due to update
umask 2
while true; do
    /usr/bin/get_iplayer --refresh --verbose
    if [ -z "$BASEURL" ]; then
        su-exec $PUID:$PGID /usr/share/get_iplayer/get_iplayer.cgi -p $PORT;
    else
        su-exec $PUID:$PGID /usr/share/get_iplayer/get_iplayer.cgi -p $PORT -b "$BASEURL";
    fi
done
